# Generated by Django 5.1.5 on 2025-03-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_subscription_end_date_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the subscription in days ', null=True),
        ),
    ]
