# Generated by Django 5.1.5 on 2025-04-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexercise',
            name='beat_times',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
