# Generated by Django 5.1.5 on 2025-04-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_testexercise_beat_times'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testexercise',
            options={'verbose_name': 'Breathing Beats', 'verbose_name_plural': 'Breathing Beats'},
        ),
    ]
