# Generated by Django 5.1.5 on 2025-01-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('hobby', models.TextField(blank=True, null=True)),
                ('favourite_artist', models.CharField(blank=True, max_length=100, null=True)),
                ('goal', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
