# Generated by Django 5.1.5 on 2025-02-04 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_userdata_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('practice_frequency', models.CharField(choices=[('1', 'Once a week'), ('2', 'Twice a week'), ('3', 'Three times a week'), ('4', 'Four times a week'), ('5', 'Five times a week'), ('6', 'Six times a week'), ('7', 'Every day')], max_length=10)),
                ('preferred_time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=20)),
                ('allow_notifications', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('goal', models.CharField(choices=[('relaxation', 'Relaxation'), ('focus', 'Better focus'), ('sleep', 'Improve sleep'), ('stress', 'Reduce stress'), ('energy', 'Increase energy')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
