# Generated by Django 5.1.5 on 2025-03-08 17:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0014_silentexercise_vibration_cues'),
        ('musicapp', '0010_musictrack_bpm'),
        ('userdata', '0004_habitpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_time_spent', models.PositiveIntegerField(default=0, help_text='Total active time in seconds')),
                ('total_exercise_time', models.PositiveIntegerField(default=0, help_text='Total time spent on exercises (in seconds)')),
                ('total_breaths', models.PositiveIntegerField(default=0, help_text='Total number of breaths during exercises')),
                ('weekly_time_spent', models.PositiveIntegerField(default=0, help_text='Total time spent this week (seconds)')),
                ('lifetime_exercises', models.PositiveIntegerField(default=0, help_text='Total exercises done in lifetime')),
                ('lifetime_music_played', models.PositiveIntegerField(default=0, help_text='Total music played in lifetime')),
                ('most_performed_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most_performed', to='breathxapp.silentexercise')),
                ('most_played_music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most_played', to='musicapp.musictrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
