# Generated by Django 5.1.5 on 2025-03-08 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0014_silentexercise_vibration_cues'),
        ('musicapp', '0010_musictrack_bpm'),
        ('userdata', '0005_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='lifetime_exercises',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='lifetime_music_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='most_performed_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='breathxapp.silentexercise'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='most_played_music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicapp.musictrack'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='total_breaths',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='total_exercise_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='total_time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='weekly_time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
