# Generated by Django 5.1.5 on 2025-03-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_alter_useractivity_lifetime_exercises_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
