# Generated by Django 5.1.5 on 2025-01-15 04:37

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_course_duration_course_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='content_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
