# Generated by Django 5.1.5 on 2025-02-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SilentSessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_length', models.PositiveIntegerField(help_text='Time in seconds')),
                ('num_breaths', models.PositiveIntegerField(help_text='Total number of breaths')),
                ('shapes_used', models.CharField(choices=[('circle', 'Circle'), ('rectangle', 'Rectangle'), ('triangle', 'Triangle'), ('square', 'Square'), ('upper_rectangle', 'Upper Rectangle')], help_text='Shape used during the session', max_length=20)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('vibration_intensity', models.PositiveIntegerField(default=5, help_text='Vibration intensity (scale 1-10)')),
                ('vibration_queue', models.TextField(help_text='List of vibration events over time, e.g., [1, 2, 3, 4]')),
            ],
        ),
    ]
