# Generated by Django 5.1.5 on 2025-02-04 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silentsessionexercise',
            name='shapes_used',
        ),
        migrations.RemoveField(
            model_name='silentsessionexercise',
            name='vibration_intensity',
        ),
        migrations.RemoveField(
            model_name='silentsessionexercise',
            name='vibration_queue',
        ),
        migrations.CreateModel(
            name='VibrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField(help_text='Time at which vibration occurs (in seconds)')),
                ('shape', models.CharField(choices=[('circle', 'Circle'), ('rectangle', 'Rectangle'), ('triangle', 'Triangle'), ('square', 'Square'), ('upper_rectangle', 'Upper Rectangle')], help_text='Shape used during vibration event', max_length=20)),
                ('intensity', models.PositiveIntegerField(default=5, help_text='Vibration intensity (scale 1-10)')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibration_events', to='breathxapp.silentsessionexercise')),
            ],
        ),
    ]
