# Generated by Django 5.1.5 on 2025-02-04 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0002_remove_silentsessionexercise_shapes_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VibrationPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.JSONField(help_text='List of vibration events. Each event contains time, shape, and intensity.')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibration_patterns', to='breathxapp.silentsessionexercise')),
            ],
        ),
        migrations.AddField(
            model_name='silentsessionexercise',
            name='vibration_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='breathxapp.vibrationpattern'),
        ),
        migrations.DeleteModel(
            name='VibrationEvent',
        ),
    ]
