# Generated by Django 5.1.5 on 2025-02-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0003_vibrationpattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibrationpattern',
            name='events',
            field=models.JSONField(help_text='List of vibration events, each contains time, intensity, and duration.'),
        ),
    ]
