# Generated by Django 5.1.5 on 2025-02-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0004_alter_vibrationpattern_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vibrationpattern',
            name='exercise',
        ),
        migrations.DeleteModel(
            name='SilentSessionExercise',
        ),
        migrations.DeleteModel(
            name='VibrationPattern',
        ),
    ]
