# Generated by Django 5.1.5 on 2025-02-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breathxapp', '0005_remove_vibrationpattern_exercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilentExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_time', models.PositiveIntegerField(help_text='Total duration in seconds')),
                ('breaths', models.PositiveIntegerField()),
                ('skill_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=15)),
                ('shapes', models.JSONField(help_text='List of shapes used (circle, square, etc.)')),
                ('vibration_cues', models.TextField(blank=True, help_text='Vibration timeline (set visually)')),
            ],
        ),
    ]
