# Generated by Django 5.1.5 on 2025-02-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silentexercise',
            name='shapes',
        ),
        migrations.AddField(
            model_name='silentexercise',
            name='shape',
            field=models.CharField(choices=[('Circle', 'Circle'), ('Square', 'Square'), ('Rectangle', 'Rectangle'), ('Triangle', 'Triangle')], default=2, help_text='Shape associated with the vibration cue', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='silentexercise',
            name='total_time',
            field=models.PositiveIntegerField(help_text='Total duration in seconds (e.g., 120 for 2 minutes)'),
        ),
        migrations.AlterField(
            model_name='silentexercise',
            name='vibration_cues',
            field=models.JSONField(default=list, help_text='List of vibration cues in seconds (e.g., [10, 30, 45])'),
        ),
    ]
