# Generated by Django 5.1.5 on 2025-02-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0007_remove_silentexercise_shapes_silentexercise_shape_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silentexercise',
            name='vibration_cues',
            field=models.CharField(help_text='Enter vibration cues as comma-separated values (e.g., 10, 20, 25)', max_length=255),
        ),
    ]
