# Generated by Django 5.1.5 on 2025-02-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0008_alter_silentexercise_vibration_cues'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('zoom_link', models.URLField(blank=True, null=True)),
                ('admin_message', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
