# Generated by Django 5.1.5 on 2025-03-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0011_silentexercise_bpm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silentexercise',
            name='bpm',
        ),
    ]
