# Generated by Django 5.1.5 on 2025-03-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0012_remove_silentexercise_bpm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silentexercise',
            name='vibration_cues',
        ),
        migrations.AddField(
            model_name='silentexercise',
            name='vibration_pattern',
            field=models.CharField(blank=True, help_text='Choose the vibration pattern based on the music scale', max_length=20, null=True),
        ),
    ]
