# Generated by Django 5.1.5 on 2025-03-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0013_remove_silentexercise_vibration_cues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='silentexercise',
            name='vibration_cues',
            field=models.CharField(blank=True, help_text='Enter vibration cues as comma-separated values (e.g., 10, 20, 25)', max_length=255, null=True),
        ),
    ]
