# Generated by Django 5.1.5 on 2025-03-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0015_silentsaveexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silentsaveexercise',
            name='inputs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='silentsaveexercise',
            name='nickname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='silentsaveexercise',
            name='shape',
            field=models.CharField(max_length=50),
        ),
    ]
