# Generated by Django 5.1.5 on 2025-03-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0016_alter_silentsaveexercise_inputs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('total_duration', models.IntegerField(help_text='Total duration in seconds')),
                ('phases', models.JSONField(help_text='List of breathing phases in JSON format')),
            ],
        ),
    ]
