# Generated by Django 5.1.5 on 2025-03-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0017_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='phases',
            field=models.JSONField(help_text='\n        Enter a list of phases as JSON. Example:\n        [\n            {"shape": "Circle", "bpm": 4, "duration": 60, "hold_time": 0},\n            {"shape": "Rectangle", "bpm": 6, "duration": 60, "hold_time": 0},\n            {"shape": "None", "bpm": 0, "duration": 60, "hold_time": 60}\n        ]\n    '),
        ),
    ]
