# Generated by Django 5.1.5 on 2025-03-27 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0018_alter_exercise_phases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='phases',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='total_duration',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50),
        ),
        migrations.CreateModel(
            name='ExercisePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('Circle', 'Circle'), ('Square', 'Square'), ('Rectangle', 'Rectangle'), ('Triangle', 'Triangle'), ('Oval', 'Oval'), ('None', 'Hold')], max_length=20)),
                ('bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('hold_time', models.PositiveIntegerField(default=0, help_text='Time to hold breath (0 if none)')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='breathxapp.exercise')),
            ],
        ),
    ]
