# Generated by Django 5.1.5 on 2025-03-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0019_remove_exercise_phases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisephase',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Duration in minutes (minimum 1)'),
        ),
        migrations.AlterField(
            model_name='exercisephase',
            name='hold_time',
            field=models.PositiveIntegerField(default=0, help_text='Time to hold breath (in seconds, 0 if none)'),
        ),
    ]
