# Generated by Django 5.1.5 on 2025-03-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0020_alter_exercisephase_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Medium', 'Medium'), ('Advanced', 'Advanced')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exercisephase',
            name='shape',
            field=models.CharField(choices=[('Circle', 'Circle'), ('Square', 'Square'), ('Rectangle', 'Rectangle'), ('Triangle', 'Triangle'), ('Oval', 'Oval'), ('ReversedTriangle', 'ReversedTriangle'), ('Quadrilateral', 'Quadrilateral')], max_length=20),
        ),
    ]
