# Generated by Django 5.1.5 on 2025-03-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0021_alter_exercise_difficulty_alter_exercisephase_shape'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisephase',
            old_name='bpm',
            new_name='input1',
        ),
        migrations.AddField(
            model_name='exercisephase',
            name='input2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisephase',
            name='input3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisephase',
            name='input4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
