# Generated by Django 5.1.5 on 2025-03-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0022_rename_bpm_exercisephase_input1_exercisephase_input2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisephase',
            old_name='input1',
            new_name='bpm',
        ),
        migrations.RemoveField(
            model_name='exercisephase',
            name='input2',
        ),
        migrations.RemoveField(
            model_name='exercisephase',
            name='input3',
        ),
        migrations.RemoveField(
            model_name='exercisephase',
            name='input4',
        ),
    ]
