# Generated by Django 5.1.5 on 2025-03-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0024_rename_bpm_exercisephase_input1_exercisephase_input2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisephase',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='exercisephase',
            name='hold_time',
        ),
    ]
