# Generated by Django 5.1.5 on 2025-03-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0026_exercisephase_duration_exercisephase_hold_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisephase',
            name='duration',
        ),
        migrations.AlterField(
            model_name='exercisephase',
            name='shape',
            field=models.CharField(choices=[('Circle', 'Circle (1)'), ('Square', 'Square (1)'), ('Rectangle', 'Rectangle (4)'), ('Triangle', 'Triangle (3)'), ('Oval', 'Oval (2)'), ('ReversedTriangle', 'ReversedTriangle (4)'), ('Quadrilateral', 'Quadrilateral (4)')], max_length=20),
        ),
    ]
