# Generated by Django 5.1.5 on 2025-03-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0027_remove_exercisephase_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisephase',
            name='cycles',
            field=models.PositiveIntegerField(default=1, help_text='Number of cycles to complete (minimum 1)'),
        ),
    ]
