# Generated by Django 5.1.5 on 2025-04-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathxapp', '0028_exercisephase_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisephase',
            name='shape',
            field=models.CharField(choices=[('Circle', 'Circle (1)'), ('Square', 'Square (1)'), ('Rectangle', 'Rectangle (2)'), ('Triangle', 'Triangle (3)'), ('Oval', 'Oval (2)'), ('ReversedTriangle', 'ReversedTriangle (4)'), ('Quadrilateral', 'Quadrilateral (4)')], max_length=20),
        ),
    ]
