# Generated by Django 5.1.5 on 2025-01-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='songs/')),
                ('vibration_pattern', models.CharField(choices=[('quarter', '1/4 Note'), ('half', '1/2 Note'), ('three_quarter', '3/4 Note'), ('full', 'Full Note')], help_text='Choose the vibration pattern based on the music scale', max_length=20)),
            ],
        ),
    ]
