# Generated by Django 5.1.4 on 2025-01-01 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_category_description_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictrack',
            name='artist',
            field=models.CharField(default='By admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='musicapp.category'),
        ),
    ]
