# Generated by Django 5.1.5 on 2025-01-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_musictrack_artist_alter_musictrack_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='viewcount',
            field=models.IntegerField(default=0),
        ),
    ]
