# Generated by Django 5.1.5 on 2025-01-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='vibration_pattern',
            field=models.CharField(choices=[('quarter', '1/4 Note'), ('half', '1/2 Note'), ('three_quarter', '3/4 Note'), ('full', 'Full Note')], default=2, help_text='Choose the vibration pattern based on the music scale', max_length=20),
            preserve_default=False,
        ),
    ]
