# Generated by Django 5.1.5 on 2025-02-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_musictrack_vibration_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='timestamps',
            field=models.TextField(blank=True, help_text='Comma-separated timestamps (e.g., 5,14,20)', null=True),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='vibration_pattern',
            field=models.CharField(blank=True, choices=[('quarter', '1/4 Note'), ('half', '1/2 Note'), ('three_quarter', '3/4 Note'), ('full', 'Full Note')], help_text='Choose the vibration pattern based on the music scale', max_length=20, null=True),
        ),
    ]
