# Generated by Django 5.1.5 on 2025-02-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_musictrack_timestamps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='music/images/'),
        ),
    ]
