# Generated by Django 5.1.5 on 2025-02-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_musictrack_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='vibrationset',
            field=models.CharField(choices=[('Default', 'Default'), ('Customise', 'Customise')], default='Default', max_length=10),
        ),
    ]
