# Generated by Django 5.1.5 on 2025-03-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0009_musictrack_vibrationset'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='bpm',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
