# Generated by Django 5.1.5 on 2025-04-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0010_musictrack_bpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracks', models.ManyToManyField(related_name='global_playlists', to='musicapp.musictrack')),
            ],
        ),
    ]
