# Generated by Django 5.1.5 on 2025-04-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_globalplaylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalplaylist',
            name='created_at',
        ),
    ]
