# Generated by Django 5.1.5 on 2025-04-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0013_alter_playlist_tracks'),
        ('testapp', '0004_category_testexercise_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalplaylist',
            name='tracks',
            field=models.ManyToManyField(related_name='global_playlists', to='testapp.testexercise'),
        ),
    ]
